name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server
        run: curl -s https://yt-downloader-bot.onrender.com > /dev/null